version: 1.0.{build}
image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION%
