language: cpp

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      before_install:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

    - compiler: clang
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
      before_install:
        - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang-10 90

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER}
  - cmake --build .
